// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchxfgeHj3OsSzdBI1fihTZhp26kplSng',
    appId: '1:100248436474:web:3d22c388f9df4e126b9343',
    messagingSenderId: '100248436474',
    projectId: 'mobile-736f0',
    authDomain: 'mobile-736f0.firebaseapp.com',
    storageBucket: 'mobile-736f0.appspot.com',
    measurementId: 'G-DYHY5SKR8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjfq0fiyx8-VhHWnGF-JQ7ddqcZghIzw',
    appId: '1:100248436474:android:b2be7908b64f23126b9343',
    messagingSenderId: '100248436474',
    projectId: 'mobile-736f0',
    storageBucket: 'mobile-736f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLmj2-N0PCwyKAz0nvUKY4wrLi70pyRs',
    appId: '1:100248436474:ios:9a29c5404ec2d3596b9343',
    messagingSenderId: '100248436474',
    projectId: 'mobile-736f0',
    storageBucket: 'mobile-736f0.appspot.com',
    iosClientId: '100248436474-d9ig8ph55mi7lhp2bk6719s2100ani0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
